name: Cypress Tests - E2E Project

on:
  push:
    branches:
      - main
    paths:
      - './**.js'
      - './**.json'
      - './**.yml'

jobs:
  e2e-project-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.0

      - name: Install dependencies
        run: npm install
        working-directory: ./

      - name: Run Cypress tests
        run: npm run cypress:headless
        working-directory: ./